/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";

export enum APITenantCreditLineCurrency {
    Eur = "EUR",
    Gbp = "GBP",
}

export class APITenantCreditLineAddress extends SpeakeasyBase {
    @SpeakeasyMetadata()
    addressLine1?: string;

    @SpeakeasyMetadata()
    addressLine2?: string;

    @SpeakeasyMetadata()
    city?: string;

    @SpeakeasyMetadata()
    country?: string;

    @SpeakeasyMetadata()
    postalCode?: string;

    @SpeakeasyMetadata()
    state?: string;
}

/**
 * Type of legal business identifier of the business, such as the SIRET in France.
 */
export enum APITenantCreditLineIdentifierType {
    Siret = "siret",
    Siren = "siren",
    VatNumber = "vat_number",
    Name = "name",
    Nif = "nif",
    Cif = "cif",
    Kvk = "kvk",
    Bsn = "bsn",
    HrNummer = "hr_nummer",
    BelgiumRegistrationNumber = "belgium_registration_number",
    Steuernummer = "steuernummer",
    LessThanNilGreaterThan = "<nil>",
}

export class APITenantCreditLineDefaultBorrower extends SpeakeasyBase {
    @SpeakeasyMetadata()
    address?: APITenantCreditLineAddress;

    @SpeakeasyMetadata()
    id?: any;

    /**
     * Legal identifier of the business, such as its SIRET in France.
     */
    @SpeakeasyMetadata()
    identifier: string;

    /**
     * Type of legal business identifier of the business, such as the SIRET in France.
     */
    @SpeakeasyMetadata()
    identifierType?: APITenantCreditLineIdentifierType;

    /**
     * Legal form of the business.
     */
    @SpeakeasyMetadata()
    legalForm?: string;

    /**
     * Legal name of the business.
     */
    @SpeakeasyMetadata()
    name?: string;

    /**
     * Name of the national organization where the business is registered. For example the RCS of Paris in France
     */
    @SpeakeasyMetadata()
    registrationBody?: string;

    /**
     * The part of the capital of a company that comes from the issue of shares, in cents.
     */
    @SpeakeasyMetadata()
    shareCapital?: number;

    /**
     * The VAT number of the business, if European
     */
    @SpeakeasyMetadata()
    vatNumber?: string;
}

export enum APITenantCreditLineDefaultBorrowerStrategy {
    Buyer = "BUYER",
    Seller = "SELLER",
    LessThanNilGreaterThan = "<nil>",
}

export class APITenantCreditLineSchemasAddress extends SpeakeasyBase {
    @SpeakeasyMetadata()
    addressLine1?: string;

    @SpeakeasyMetadata()
    addressLine2?: string;

    @SpeakeasyMetadata()
    city?: string;

    @SpeakeasyMetadata()
    country?: string;

    @SpeakeasyMetadata()
    postalCode?: string;

    @SpeakeasyMetadata()
    state?: string;
}

/**
 * Type of legal business identifier of the business, such as the SIRET in France.
 */
export enum APITenantCreditLineSchemasIdentifierType {
    Siret = "siret",
    Siren = "siren",
    VatNumber = "vat_number",
    Name = "name",
    Nif = "nif",
    Cif = "cif",
    Kvk = "kvk",
    Bsn = "bsn",
    HrNummer = "hr_nummer",
    BelgiumRegistrationNumber = "belgium_registration_number",
    Steuernummer = "steuernummer",
    LessThanNilGreaterThan = "<nil>",
}

export class APITenantCreditLineDefaultGuarantor extends SpeakeasyBase {
    @SpeakeasyMetadata()
    address?: APITenantCreditLineSchemasAddress;

    @SpeakeasyMetadata()
    id?: any;

    /**
     * Legal identifier of the business, such as its SIRET in France.
     */
    @SpeakeasyMetadata()
    identifier: string;

    /**
     * Type of legal business identifier of the business, such as the SIRET in France.
     */
    @SpeakeasyMetadata()
    identifierType?: APITenantCreditLineSchemasIdentifierType;

    /**
     * Legal form of the business.
     */
    @SpeakeasyMetadata()
    legalForm?: string;

    /**
     * Legal name of the business.
     */
    @SpeakeasyMetadata()
    name?: string;

    /**
     * Name of the national organization where the business is registered. For example the RCS of Paris in France
     */
    @SpeakeasyMetadata()
    registrationBody?: string;

    /**
     * The part of the capital of a company that comes from the issue of shares, in cents.
     */
    @SpeakeasyMetadata()
    shareCapital?: number;

    /**
     * The VAT number of the business, if European
     */
    @SpeakeasyMetadata()
    vatNumber?: string;
}

/**
 * The type of account number (e.g. IBAN).
 */
export enum APITenantCreditLineAccountNumberType {
    Iban = "iban",
    AccountNumber = "account_number",
    InternalId = "internal_id",
}

/**
 * The type of bank identifier (e.g. BIC).
 */
export enum APITenantCreditLineBankIdentifierType {
    Bic = "bic",
    RoutingNumber = "routing_number",
    Name = "name",
}

export class APITenantCreditLineDefaultLoanFrom extends SpeakeasyBase {
    /**
     * The account identifier. Only IBANs are supported at the moment.
     */
    @SpeakeasyMetadata()
    accountNumber: string;

    /**
     * The type of account number (e.g. IBAN).
     */
    @SpeakeasyMetadata()
    accountNumberType: APITenantCreditLineAccountNumberType;

    /**
     * The identifier of the bank.
     */
    @SpeakeasyMetadata()
    bankIdentifier: string;

    /**
     * The type of bank identifier (e.g. BIC).
     */
    @SpeakeasyMetadata()
    bankIdentifierType: APITenantCreditLineBankIdentifierType;
}

/**
 * The type of account number (e.g. IBAN).
 */
export enum APITenantCreditLineSchemasAccountNumberType {
    Iban = "iban",
    AccountNumber = "account_number",
    InternalId = "internal_id",
}

/**
 * The type of bank identifier (e.g. BIC).
 */
export enum APITenantCreditLineSchemasBankIdentifierType {
    Bic = "bic",
    RoutingNumber = "routing_number",
    Name = "name",
}

export class APITenantCreditLineDefaultRepaymentFrom extends SpeakeasyBase {
    /**
     * The account identifier. Only IBANs are supported at the moment.
     */
    @SpeakeasyMetadata()
    accountNumber: string;

    /**
     * The type of account number (e.g. IBAN).
     */
    @SpeakeasyMetadata()
    accountNumberType: APITenantCreditLineSchemasAccountNumberType;

    /**
     * The identifier of the bank.
     */
    @SpeakeasyMetadata()
    bankIdentifier: string;

    /**
     * The type of bank identifier (e.g. BIC).
     */
    @SpeakeasyMetadata()
    bankIdentifierType: APITenantCreditLineSchemasBankIdentifierType;
}

export enum APITenantCreditLineDefaultRepaymentMethod {
    DirectDebit = "DIRECT_DEBIT",
    Sct = "SCT",
    P2P = "P2P",
}

/**
 * The type of account number (e.g. IBAN).
 */
export enum APITenantCreditLineSchemasDefaultRepaymentToAccountNumberType {
    Iban = "iban",
    AccountNumber = "account_number",
    InternalId = "internal_id",
}

/**
 * The type of bank identifier (e.g. BIC).
 */
export enum APITenantCreditLineSchemasDefaultRepaymentToBankIdentifierType {
    Bic = "bic",
    RoutingNumber = "routing_number",
    Name = "name",
}

export class APITenantCreditLineDefaultRepaymentTo extends SpeakeasyBase {
    /**
     * The account identifier. Only IBANs are supported at the moment.
     */
    @SpeakeasyMetadata()
    accountNumber: string;

    /**
     * The type of account number (e.g. IBAN).
     */
    @SpeakeasyMetadata()
    accountNumberType: APITenantCreditLineSchemasDefaultRepaymentToAccountNumberType;

    /**
     * The identifier of the bank.
     */
    @SpeakeasyMetadata()
    bankIdentifier: string;

    /**
     * The type of bank identifier (e.g. BIC).
     */
    @SpeakeasyMetadata()
    bankIdentifierType: APITenantCreditLineSchemasDefaultRepaymentToBankIdentifierType;
}

export enum APITenantCreditLineDistribution {
    Direct = "DIRECT",
    Partner = "PARTNER",
}

export class APITenantCreditLineSchemasFeesPayerAddress extends SpeakeasyBase {
    @SpeakeasyMetadata()
    addressLine1?: string;

    @SpeakeasyMetadata()
    addressLine2?: string;

    @SpeakeasyMetadata()
    city?: string;

    @SpeakeasyMetadata()
    country?: string;

    @SpeakeasyMetadata()
    postalCode?: string;

    @SpeakeasyMetadata()
    state?: string;
}

/**
 * Type of legal business identifier of the business, such as the SIRET in France.
 */
export enum APITenantCreditLineSchemasFeesPayerIdentifierType {
    Siret = "siret",
    Siren = "siren",
    VatNumber = "vat_number",
    Name = "name",
    Nif = "nif",
    Cif = "cif",
    Kvk = "kvk",
    Bsn = "bsn",
    HrNummer = "hr_nummer",
    BelgiumRegistrationNumber = "belgium_registration_number",
    Steuernummer = "steuernummer",
    LessThanNilGreaterThan = "<nil>",
}

export class APITenantCreditLineFeesPayer extends SpeakeasyBase {
    @SpeakeasyMetadata()
    address?: APITenantCreditLineSchemasFeesPayerAddress;

    @SpeakeasyMetadata()
    id?: any;

    /**
     * Legal identifier of the business, such as its SIRET in France.
     */
    @SpeakeasyMetadata()
    identifier: string;

    /**
     * Type of legal business identifier of the business, such as the SIRET in France.
     */
    @SpeakeasyMetadata()
    identifierType?: APITenantCreditLineSchemasFeesPayerIdentifierType;

    /**
     * Legal form of the business.
     */
    @SpeakeasyMetadata()
    legalForm?: string;

    /**
     * Legal name of the business.
     */
    @SpeakeasyMetadata()
    name?: string;

    /**
     * Name of the national organization where the business is registered. For example the RCS of Paris in France
     */
    @SpeakeasyMetadata()
    registrationBody?: string;

    /**
     * The part of the capital of a company that comes from the issue of shares, in cents.
     */
    @SpeakeasyMetadata()
    shareCapital?: number;

    /**
     * The VAT number of the business, if European
     */
    @SpeakeasyMetadata()
    vatNumber?: string;
}

export class APITenantCreditLine extends SpeakeasyBase {
    @SpeakeasyMetadata()
    amountToRepay?: number;

    /**
     * Remaining amount that can be loaned.
     */
    @SpeakeasyMetadata()
    balanceAvailable?: number;

    @SpeakeasyMetadata()
    balancePending?: number;

    @SpeakeasyMetadata()
    comingUpMonthlyFees?: number;

    @SpeakeasyMetadata()
    contractNumber?: string;

    @SpeakeasyMetadata()
    currency?: APITenantCreditLineCurrency;

    @SpeakeasyMetadata()
    defaultBorrower?: APITenantCreditLineDefaultBorrower;

    @SpeakeasyMetadata()
    defaultBorrowerStrategy?: APITenantCreditLineDefaultBorrowerStrategy;

    @SpeakeasyMetadata()
    defaultGuarantor?: APITenantCreditLineDefaultGuarantor;

    @SpeakeasyMetadata()
    defaultLoanFrom?: APITenantCreditLineDefaultLoanFrom;

    @SpeakeasyMetadata()
    defaultRepaymentFrom?: APITenantCreditLineDefaultRepaymentFrom;

    @SpeakeasyMetadata()
    defaultRepaymentMethod?: APITenantCreditLineDefaultRepaymentMethod;

    @SpeakeasyMetadata()
    defaultRepaymentTo?: APITenantCreditLineDefaultRepaymentTo;

    @SpeakeasyMetadata()
    distribution: APITenantCreditLineDistribution;

    @SpeakeasyMetadata()
    endDate?: Date;

    @SpeakeasyMetadata()
    feesDailyRate?: number;

    @SpeakeasyMetadata()
    feesInterestDailyRate: number;

    @SpeakeasyMetadata()
    feesOperatingDailyRate: number;

    @SpeakeasyMetadata()
    feesPayer?: APITenantCreditLineFeesPayer;

    @SpeakeasyMetadata()
    id?: any;

    /**
     * Maximum amount that can be loaned.
     */
    @SpeakeasyMetadata()
    poolAmount?: number;

    @SpeakeasyMetadata()
    signedAt?: Date;

    @SpeakeasyMetadata()
    startDate: Date;

    @SpeakeasyMetadata()
    vat?: number;
}
