/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";

export enum APITenantCreditLineCurrencyEnum {
  Eur = "EUR",
  Gbp = "GBP",
}

export class APITenantCreditLineDefaultBorrowerAddress extends SpeakeasyBase {
  @SpeakeasyMetadata()
  addressLine1?: string;

  @SpeakeasyMetadata()
  addressLine2?: string;

  @SpeakeasyMetadata()
  city?: string;

  @SpeakeasyMetadata()
  country?: string;

  @SpeakeasyMetadata()
  postalCode?: string;

  @SpeakeasyMetadata()
  state?: string;
}

/**
 * Type of legal business identifier of the business, such as the SIRET in France.
 */
export enum APITenantCreditLineDefaultBorrowerIdentifierTypeEnum {
  Siret = "siret",
  Siren = "siren",
  VatNumber = "vat_number",
  Name = "name",
  Nif = "nif",
  Cif = "cif",
  Kvk = "kvk",
  Bsn = "bsn",
  HrNummer = "hr_nummer",
  BelgiumRegistrationNumber = "belgium_registration_number",
  Steuernummer = "steuernummer",
  LessThanNilGreaterThan = "<nil>",
}

export class APITenantCreditLineDefaultBorrower extends SpeakeasyBase {
  @SpeakeasyMetadata()
  address?: APITenantCreditLineDefaultBorrowerAddress;

  @SpeakeasyMetadata()
  id?: any;

  /**
   * Legal identifier of the business, such as its SIRET in France.
   */
  @SpeakeasyMetadata()
  identifier: string;

  /**
   * Type of legal business identifier of the business, such as the SIRET in France.
   */
  @SpeakeasyMetadata()
  identifierType?: APITenantCreditLineDefaultBorrowerIdentifierTypeEnum;

  /**
   * Legal form of the business.
   */
  @SpeakeasyMetadata()
  legalForm?: string;

  /**
   * Legal name of the business.
   */
  @SpeakeasyMetadata()
  name?: string;

  /**
   * Name of the national organization where the business is registered. For example the RCS of Paris in France
   */
  @SpeakeasyMetadata()
  registrationBody?: string;

  /**
   * The part of the capital of a company that comes from the issue of shares, in cents.
   */
  @SpeakeasyMetadata()
  shareCapital?: number;

  /**
   * The VAT number of the business, if European
   */
  @SpeakeasyMetadata()
  vatNumber?: string;
}

export enum APITenantCreditLineDefaultBorrowerStrategyEnum {
  Buyer = "BUYER",
  Seller = "SELLER",
  LessThanNilGreaterThan = "<nil>",
}

export class APITenantCreditLineDefaultGuarantorAddress extends SpeakeasyBase {
  @SpeakeasyMetadata()
  addressLine1?: string;

  @SpeakeasyMetadata()
  addressLine2?: string;

  @SpeakeasyMetadata()
  city?: string;

  @SpeakeasyMetadata()
  country?: string;

  @SpeakeasyMetadata()
  postalCode?: string;

  @SpeakeasyMetadata()
  state?: string;
}

/**
 * Type of legal business identifier of the business, such as the SIRET in France.
 */
export enum APITenantCreditLineDefaultGuarantorIdentifierTypeEnum {
  Siret = "siret",
  Siren = "siren",
  VatNumber = "vat_number",
  Name = "name",
  Nif = "nif",
  Cif = "cif",
  Kvk = "kvk",
  Bsn = "bsn",
  HrNummer = "hr_nummer",
  BelgiumRegistrationNumber = "belgium_registration_number",
  Steuernummer = "steuernummer",
  LessThanNilGreaterThan = "<nil>",
}

export class APITenantCreditLineDefaultGuarantor extends SpeakeasyBase {
  @SpeakeasyMetadata()
  address?: APITenantCreditLineDefaultGuarantorAddress;

  @SpeakeasyMetadata()
  id?: any;

  /**
   * Legal identifier of the business, such as its SIRET in France.
   */
  @SpeakeasyMetadata()
  identifier: string;

  /**
   * Type of legal business identifier of the business, such as the SIRET in France.
   */
  @SpeakeasyMetadata()
  identifierType?: APITenantCreditLineDefaultGuarantorIdentifierTypeEnum;

  /**
   * Legal form of the business.
   */
  @SpeakeasyMetadata()
  legalForm?: string;

  /**
   * Legal name of the business.
   */
  @SpeakeasyMetadata()
  name?: string;

  /**
   * Name of the national organization where the business is registered. For example the RCS of Paris in France
   */
  @SpeakeasyMetadata()
  registrationBody?: string;

  /**
   * The part of the capital of a company that comes from the issue of shares, in cents.
   */
  @SpeakeasyMetadata()
  shareCapital?: number;

  /**
   * The VAT number of the business, if European
   */
  @SpeakeasyMetadata()
  vatNumber?: string;
}

/**
 * The type of account number (e.g. IBAN).
 */
export enum APITenantCreditLineDefaultLoanFromAccountNumberTypeEnum {
  Iban = "iban",
  AccountNumber = "account_number",
  InternalId = "internal_id",
}

/**
 * The type of bank identifier (e.g. BIC).
 */
export enum APITenantCreditLineDefaultLoanFromBankIdentifierTypeEnum {
  Bic = "bic",
  RoutingNumber = "routing_number",
  Name = "name",
}

export class APITenantCreditLineDefaultLoanFrom extends SpeakeasyBase {
  /**
   * The account identifier. Only IBANs are supported at the moment.
   */
  @SpeakeasyMetadata()
  accountNumber: string;

  /**
   * The type of account number (e.g. IBAN).
   */
  @SpeakeasyMetadata()
  accountNumberType: APITenantCreditLineDefaultLoanFromAccountNumberTypeEnum;

  /**
   * The identifier of the bank.
   */
  @SpeakeasyMetadata()
  bankIdentifier: string;

  /**
   * The type of bank identifier (e.g. BIC).
   */
  @SpeakeasyMetadata()
  bankIdentifierType: APITenantCreditLineDefaultLoanFromBankIdentifierTypeEnum;
}

/**
 * The type of account number (e.g. IBAN).
 */
export enum APITenantCreditLineDefaultRepaymentFromAccountNumberTypeEnum {
  Iban = "iban",
  AccountNumber = "account_number",
  InternalId = "internal_id",
}

/**
 * The type of bank identifier (e.g. BIC).
 */
export enum APITenantCreditLineDefaultRepaymentFromBankIdentifierTypeEnum {
  Bic = "bic",
  RoutingNumber = "routing_number",
  Name = "name",
}

export class APITenantCreditLineDefaultRepaymentFrom extends SpeakeasyBase {
  /**
   * The account identifier. Only IBANs are supported at the moment.
   */
  @SpeakeasyMetadata()
  accountNumber: string;

  /**
   * The type of account number (e.g. IBAN).
   */
  @SpeakeasyMetadata()
  accountNumberType: APITenantCreditLineDefaultRepaymentFromAccountNumberTypeEnum;

  /**
   * The identifier of the bank.
   */
  @SpeakeasyMetadata()
  bankIdentifier: string;

  /**
   * The type of bank identifier (e.g. BIC).
   */
  @SpeakeasyMetadata()
  bankIdentifierType: APITenantCreditLineDefaultRepaymentFromBankIdentifierTypeEnum;
}

export enum APITenantCreditLineDefaultRepaymentMethodEnum {
  DirectDebit = "DIRECT_DEBIT",
  Sct = "SCT",
  P2P = "P2P",
}

/**
 * The type of account number (e.g. IBAN).
 */
export enum APITenantCreditLineDefaultRepaymentToAccountNumberTypeEnum {
  Iban = "iban",
  AccountNumber = "account_number",
  InternalId = "internal_id",
}

/**
 * The type of bank identifier (e.g. BIC).
 */
export enum APITenantCreditLineDefaultRepaymentToBankIdentifierTypeEnum {
  Bic = "bic",
  RoutingNumber = "routing_number",
  Name = "name",
}

export class APITenantCreditLineDefaultRepaymentTo extends SpeakeasyBase {
  /**
   * The account identifier. Only IBANs are supported at the moment.
   */
  @SpeakeasyMetadata()
  accountNumber: string;

  /**
   * The type of account number (e.g. IBAN).
   */
  @SpeakeasyMetadata()
  accountNumberType: APITenantCreditLineDefaultRepaymentToAccountNumberTypeEnum;

  /**
   * The identifier of the bank.
   */
  @SpeakeasyMetadata()
  bankIdentifier: string;

  /**
   * The type of bank identifier (e.g. BIC).
   */
  @SpeakeasyMetadata()
  bankIdentifierType: APITenantCreditLineDefaultRepaymentToBankIdentifierTypeEnum;
}

export enum APITenantCreditLineDistributionEnum {
  Direct = "DIRECT",
  Partner = "PARTNER",
}

export class APITenantCreditLineFeesPayerAddress extends SpeakeasyBase {
  @SpeakeasyMetadata()
  addressLine1?: string;

  @SpeakeasyMetadata()
  addressLine2?: string;

  @SpeakeasyMetadata()
  city?: string;

  @SpeakeasyMetadata()
  country?: string;

  @SpeakeasyMetadata()
  postalCode?: string;

  @SpeakeasyMetadata()
  state?: string;
}

/**
 * Type of legal business identifier of the business, such as the SIRET in France.
 */
export enum APITenantCreditLineFeesPayerIdentifierTypeEnum {
  Siret = "siret",
  Siren = "siren",
  VatNumber = "vat_number",
  Name = "name",
  Nif = "nif",
  Cif = "cif",
  Kvk = "kvk",
  Bsn = "bsn",
  HrNummer = "hr_nummer",
  BelgiumRegistrationNumber = "belgium_registration_number",
  Steuernummer = "steuernummer",
  LessThanNilGreaterThan = "<nil>",
}

export class APITenantCreditLineFeesPayer extends SpeakeasyBase {
  @SpeakeasyMetadata()
  address?: APITenantCreditLineFeesPayerAddress;

  @SpeakeasyMetadata()
  id?: any;

  /**
   * Legal identifier of the business, such as its SIRET in France.
   */
  @SpeakeasyMetadata()
  identifier: string;

  /**
   * Type of legal business identifier of the business, such as the SIRET in France.
   */
  @SpeakeasyMetadata()
  identifierType?: APITenantCreditLineFeesPayerIdentifierTypeEnum;

  /**
   * Legal form of the business.
   */
  @SpeakeasyMetadata()
  legalForm?: string;

  /**
   * Legal name of the business.
   */
  @SpeakeasyMetadata()
  name?: string;

  /**
   * Name of the national organization where the business is registered. For example the RCS of Paris in France
   */
  @SpeakeasyMetadata()
  registrationBody?: string;

  /**
   * The part of the capital of a company that comes from the issue of shares, in cents.
   */
  @SpeakeasyMetadata()
  shareCapital?: number;

  /**
   * The VAT number of the business, if European
   */
  @SpeakeasyMetadata()
  vatNumber?: string;
}

export class APITenantCreditLine extends SpeakeasyBase {
  @SpeakeasyMetadata()
  amountToRepay?: number;

  /**
   * Remaining amount that can be loaned.
   */
  @SpeakeasyMetadata()
  balanceAvailable?: number;

  @SpeakeasyMetadata()
  balancePending?: number;

  @SpeakeasyMetadata()
  comingUpMonthlyFees?: number;

  @SpeakeasyMetadata()
  contractNumber?: string;

  @SpeakeasyMetadata()
  currency?: APITenantCreditLineCurrencyEnum;

  @SpeakeasyMetadata()
  defaultBorrower?: APITenantCreditLineDefaultBorrower;

  @SpeakeasyMetadata()
  defaultBorrowerStrategy?: APITenantCreditLineDefaultBorrowerStrategyEnum;

  @SpeakeasyMetadata()
  defaultGuarantor?: APITenantCreditLineDefaultGuarantor;

  @SpeakeasyMetadata()
  defaultLoanFrom?: APITenantCreditLineDefaultLoanFrom;

  @SpeakeasyMetadata()
  defaultRepaymentFrom?: APITenantCreditLineDefaultRepaymentFrom;

  @SpeakeasyMetadata()
  defaultRepaymentMethod?: APITenantCreditLineDefaultRepaymentMethodEnum;

  @SpeakeasyMetadata()
  defaultRepaymentTo?: APITenantCreditLineDefaultRepaymentTo;

  @SpeakeasyMetadata()
  distribution: APITenantCreditLineDistributionEnum;

  @SpeakeasyMetadata()
  endDate?: Date;

  @SpeakeasyMetadata()
  feesDailyRate?: number;

  @SpeakeasyMetadata()
  feesInterestDailyRate: number;

  @SpeakeasyMetadata()
  feesOperatingDailyRate: number;

  @SpeakeasyMetadata()
  feesPayer?: APITenantCreditLineFeesPayer;

  @SpeakeasyMetadata()
  id?: any;

  /**
   * Maximum amount that can be loaned.
   */
  @SpeakeasyMetadata()
  poolAmount?: number;

  @SpeakeasyMetadata()
  signedAt?: Date;

  @SpeakeasyMetadata()
  startDate: Date;

  @SpeakeasyMetadata()
  vat?: number;
}
