/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";

export class GenerateIbanResponse extends SpeakeasyBase {
    @SpeakeasyMetadata()
    iban: string;
}
