/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

export enum SellerBusinessIdentifierIdentifierType {
    Siret = "siret",
    Siren = "siren",
    VatNumber = "vat_number",
    Name = "name",
    Nif = "nif",
    Cif = "cif",
    Kvk = "kvk",
    Bsn = "bsn",
    HrNummer = "hr_nummer",
    BelgiumRegistrationNumber = "belgium_registration_number",
    Steuernummer = "steuernummer",
}

export class SellerBusinessIdentifier extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "identifier" })
    identifier: string;

    @SpeakeasyMetadata()
    @Expose({ name: "identifier_type" })
    identifierType: SellerBusinessIdentifierIdentifierType;
}
