/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { APICreditLine } from "./apicreditline";

export class TypedApiPage5 extends SpeakeasyBase {
    @SpeakeasyMetadata()
    count: number;

    @SpeakeasyMetadata({ elemType: APICreditLine })
    data?: APICreditLine[];

    @SpeakeasyMetadata()
    nextPage?: string;

    @SpeakeasyMetadata()
    pageSize: number;
}
