/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { APIInvoice } from "./apiinvoice";

export class TypedApiPage1 extends SpeakeasyBase {
    @SpeakeasyMetadata()
    count: number;

    @SpeakeasyMetadata({ elemType: APIInvoice })
    data?: APIInvoice[];

    @SpeakeasyMetadata()
    nextPage?: string;

    @SpeakeasyMetadata()
    pageSize: number;
}
