/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { APIBill } from "./apibill";

export class TypedApiPage7 extends SpeakeasyBase {
  @SpeakeasyMetadata()
  count: number;

  @SpeakeasyMetadata({ elemType: APIBill })
  data?: APIBill[];

  @SpeakeasyMetadata()
  nextPage?: string;

  @SpeakeasyMetadata()
  pageSize: number;
}
