/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { LoanAPI } from "./loanapi";

export class TypedApiPage2 extends SpeakeasyBase {
    @SpeakeasyMetadata()
    count: number;

    @SpeakeasyMetadata({ elemType: LoanAPI })
    data?: LoanAPI[];

    @SpeakeasyMetadata()
    nextPage?: string;

    @SpeakeasyMetadata()
    pageSize: number;
}
