/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { AxiosResponse } from "axios";

export enum QueryParamCountry {
    Fra = "FRA",
    Esp = "ESP",
    Nld = "NLD",
    Deu = "DEU",
    Bel = "BEL",
}

export enum Scenario {
    Success = "SUCCESS",
    SuccessOneDayLater = "SUCCESS_ONE_DAY_LATER",
    Reject = "REJECT",
    Fail = "FAIL",
}

export class GenerateIbanRequest extends SpeakeasyBase {
    @SpeakeasyMetadata({ data: "queryParam, style=form;explode=true;name=country" })
    country?: QueryParamCountry;

    @SpeakeasyMetadata({ data: "queryParam, style=form;explode=true;name=scenario" })
    scenario?: Scenario;
}

export class GenerateIbanResponse extends SpeakeasyBase {
    @SpeakeasyMetadata()
    body?: Uint8Array;

    /**
     * HTTP response content type for this operation
     */
    @SpeakeasyMetadata()
    contentType: string;

    /**
     * HTTP response status code for this operation
     */
    @SpeakeasyMetadata()
    statusCode: number;

    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    @SpeakeasyMetadata()
    rawResponse: AxiosResponse;
}
