/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { AxiosResponse } from "axios";

export enum GetSandboxBusinessGeneratorCountryEnum {
  Fra = "FRA",
  Esp = "ESP",
  Nld = "NLD",
  Deu = "DEU",
  Bel = "BEL",
}

export class GetSandboxBusinessGeneratorRequest extends SpeakeasyBase {
  @SpeakeasyMetadata({
    data: "queryParam, style=form;explode=true;name=country",
  })
  country?: GetSandboxBusinessGeneratorCountryEnum;

  @SpeakeasyMetadata({
    data: "queryParam, style=form;explode=true;name=is_borrower",
  })
  isBorrower?: boolean;
}

export class GetSandboxBusinessGeneratorResponse extends SpeakeasyBase {
  @SpeakeasyMetadata()
  body?: Uint8Array;

  @SpeakeasyMetadata()
  contentType: string;

  @SpeakeasyMetadata()
  statusCode: number;

  @SpeakeasyMetadata()
  rawResponse?: AxiosResponse;
}
