/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { AxiosResponse } from "axios";

export enum GetSandboxIbanGeneratorCountryEnum {
  Fra = "FRA",
  Esp = "ESP",
  Nld = "NLD",
  Deu = "DEU",
  Bel = "BEL",
}

export enum GetSandboxIbanGeneratorScenarioEnum {
  Success = "SUCCESS",
  SuccessOneDayLater = "SUCCESS_ONE_DAY_LATER",
  Reject = "REJECT",
  Fail = "FAIL",
}

export class GetSandboxIbanGeneratorRequest extends SpeakeasyBase {
  @SpeakeasyMetadata({
    data: "queryParam, style=form;explode=true;name=country",
  })
  country?: GetSandboxIbanGeneratorCountryEnum;

  @SpeakeasyMetadata({
    data: "queryParam, style=form;explode=true;name=scenario",
  })
  scenario?: GetSandboxIbanGeneratorScenarioEnum;
}

export class GetSandboxIbanGeneratorResponse extends SpeakeasyBase {
  @SpeakeasyMetadata()
  body?: Uint8Array;

  @SpeakeasyMetadata()
  contentType: string;

  @SpeakeasyMetadata()
  statusCode: number;

  @SpeakeasyMetadata()
  rawResponse?: AxiosResponse;
}
