/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { AxiosResponse } from "axios";

export class UploadInvoicesRequest extends SpeakeasyBase {
    /**
     * Business identifier of the buyer, must be in the form - such as SIREN-899021021 for a french company.
     */
    @SpeakeasyMetadata({ data: "queryParam, style=form;explode=true;name=buyer" })
    buyer?: string;

    /**
     * Business identifier of the seller, must be in the form - such as SIREN-899021021 for a french company.
     */
    @SpeakeasyMetadata({ data: "queryParam, style=form;explode=true;name=seller" })
    seller?: string;
}

export class UploadInvoicesResponse extends SpeakeasyBase {
    @SpeakeasyMetadata()
    body?: Uint8Array;

    @SpeakeasyMetadata()
    contentType: string;

    @SpeakeasyMetadata()
    statusCode: number;

    @SpeakeasyMetadata()
    rawResponse?: AxiosResponse;
}
